name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile HOY
      run: |
        cd HOY
        make
    - name: Compile WFG
      run: |
        cd WFG
        make
    - name: Download and compile HV 1.3
      run: |
        wget https://lopez-ibanez.eu/files/hv-1.3-src.tar.gz
        tar -xzf hv-1.3-src.tar.gz
        cd hv-1.3-src
        make
    - name: Download and compile HV rc1
      run: |
        wget https://lopez-ibanez.eu/files/hv-2.0rc1-src.tar.gz
        tar -xzf hv-2.0rc1-src.tar.gz
        cd hv-2.0rc1-src
        make
    - name: Download and compile HV rc2
      run: |
        wget https://lopez-ibanez.eu/files/hv-2.0rc2-src.tar.gz
        tar -xzf hv-2.0rc2-src.tar.gz
        cd hv-2.0rc2-src
        make
    - name: Download and setup MOEA Framework
      run: |
        #VERSION=$(curl https://api.github.com/repos/MOEAFramework/MOEAFramework/releases/latest | jq '.tag_name' | grep -oEi '[0-9]+\.[0-9]+(\.[0-9]+)?')
        #wget https://github.com/MOEAFramework/MOEAFramework/releases/download/v${VERSION}/MOEAFramework-${VERSION}.tar.gz
        #tar -xzf MOEAFramework-${VERSION}.tar.gz
        #mv MOEAFramework-${VERSION} MOEAFramework-Latest
        
        git clone http://github.com/MOEAFramework/MOEAFramework
        cd MOEAFramework
        ant package-binary
        mv dist/MOEAFramework-*.tar.gz ../
        cd ..
        tar -xzf MOEAFramework-*.tar.gz
        #mv MOEAFramework-* MOEAFramework-Latest
        ls
    - name: Setup timings
      run: |
        VERSION=$(curl https://api.github.com/repos/MOEAFramework/MOEAFramework/releases/latest | jq '.tag_name' | grep -oEi '[0-9]+\.[0-9]+(\.[0-9]+)?')
        wget https://github.com/MOEAFramework/MOEAFramework/releases/download/v${VERSION}/MOEAFramework-${VERSION}.tar.gz
        tar -xzf MOEAFramework-${VERSION}.tar.gz
        mv MOEAFramework-${VERSION} MOEAFramework-Latest
        
        mv WFG/wfg0 MOEAFramework-Latest
        mv WFG/wfg1 MOEAFramework-Latest
        mv WFG/wfg2 MOEAFramework-Latest
        mv WFG/wfg3 MOEAFramework-Latest
        mv HOY/hoy MOEAFramework-Latest
        mv hv-1.3-src/hv MOEAFramework-Latest/hv1.3
        mv hv-2.0rc1-src/hv MOEAFramework-Latest/hv2.rc1
        mv hv-2.0rc2-src/hv MOEAFramework-Latest/hv2.rc2
    - name: Run timings
      run: |
        cd MOEAFramework-Latest
        
        trials=1
        inputs=(DTLZ2.2D.pf DTLZ2.3D.pf DTLZ2.4D.pf DTLZ2.6D.pf DTLZ2.8D.pf)

        function test() {
          ts=$(date +%s%N)
          #eps=0.01

          #if echo "$input" | grep ".4D." > /dev/null; then
          #  eps=0.05
          #elif echo "$input" | grep ".6D." > /dev/null; then
          #  eps=0.1
          #elif echo "$input" | grep ".8D." > /dev/null; then
          #  eps=0.2
          #fi

          for i in $(seq 1 $trials)
          do
            hv=$(java -cp ".:lib/*" org.moeaframework.analysis.sensitivity.SetHypervolume "./pf/$1")
          done

          et=$((($(date +%s%N) - $ts)/1000000))
          echo "    $hv ($et ms)"
        }

        function test_all() {
          for input in ${inputs[@]}
          do
            test "$input"
          done
        }

        #echo "Built-in..."
        #printf "" > moeaframework.properties
        #test_all
        
        #echo ""
        #echo "WFG (Variant 0)..."
        #printf "org.moeaframework.core.indicator.hypervolume = ./wfg0 {2}\norg.moeaframework.core.indicator.hypervolume_inverted = true" > moeaframework.properties
        #test_all
        
        #echo ""
        #echo "WFG (Variant 1)..."
        #printf "org.moeaframework.core.indicator.hypervolume = ./wfg1 {2}\norg.moeaframework.core.indicator.hypervolume_inverted = true" > moeaframework.properties
        #test_all

        echo ""
        echo "WFG (Variant 2)..."
        printf "org.moeaframework.core.indicator.hypervolume = ./wfg2 {2}\norg.moeaframework.core.indicator.hypervolume_inverted = true" > moeaframework.properties
        test_all
        
        #echo ""
        #echo "WFG (Variant 3)..."
        #printf "org.moeaframework.core.indicator.hypervolume = ./wfg3 {2}\norg.moeaframework.core.indicator.hypervolume_inverted = true" > moeaframework.properties
        #test_all

        # Need to investigate, this is taking really long and something might have broke...
        #echo ""
        #echo "HOY..."
        #printf "org.moeaframework.core.indicator.hypervolume = ./hoy {0} {1} {2} {3}\norg.moeaframework.core.indicator.hypervolume_inverted = false" > moeaframework.properties
        #test_all
        
        #echo ""
        #echo "HV1.3..."
        #printf "org.moeaframework.core.indicator.hypervolume = ./hv1.3 {2}\norg.moeaframework.core.indicator.hypervolume_inverted = false" > moeaframework.properties
        #test_all
        
        #echo ""
        #echo "HV2 rc1..."
        #printf "org.moeaframework.core.indicator.hypervolume = ./hv2.rc1 {2}\norg.moeaframework.core.indicator.hypervolume_inverted = false" > moeaframework.properties
        #test_all

        #echo ""
        #echo "HV2 rc2..."
        #printf "org.moeaframework.core.indicator.hypervolume = ./hv2.rc1 {2}\norg.moeaframework.core.indicator.hypervolume_inverted = false" > moeaframework.properties
        #test_all
