name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile HOY
      run: |
        cd HOY
        make
    - name: Compile WFG
      run: |
        cd WFG
        make
    - name: Download and compile HV
      run: |
        wget https://lopez-ibanez.eu/files/hv-2.0rc2-src.tar.gz
        tar -xzf hv-2.0rc2-src.tar.gz
        cd hv-2.0rc2
        make
        ls .
    - name: Setup timings
      run: |
        VERSION=$(curl https://api.github.com/repos/MOEAFramework/MOEAFramework/releases/latest | jq '.tag_name' | grep -oEi '[0-9]+\.[0-9]+(\.[0-9]+)?')
        wget https://github.com/MOEAFramework/MOEAFramework/releases/download/v${VERSION}/MOEAFramework-${VERSION}.tar.gz
        tar -xzf MOEAFramework-${VERSION}.tar.gz
        mv MOEAFramework-${VERSION} MOEAFramework-Latest
        
        mv WFG/wfg2 MOEAFramework-Latest
        mv HOY/hoy MOEAFramework-Latest
        mv hv-2.0rc2/hv MOEAFramework-Latest
    - name: Run timings
      run: |
        cd MOEAFramework-Latest

        inputs=(DTLZ2.2D.pf DTLZ2.4D.pf)

        function test() {
          ts=$(date +%s%N)
          eps=0.01

          if echo "$input" | grep ".4D."; then
            eps=0.15
          elif echo "$input" | grep ".6D."; then
            eps=0.25
          elif echo "$input" | grep ".8D."; then
            eps=0.35
          fi

          hv=$(java -cp ".:lib/*" org.moeaframework.analysis.sensitivity.SetHypervolume -e "$eps" "./pf/$1")
          et=$((($(date +%s%N) - $ts)/1000000))
          echo "    $hv ($et ms)"
        }

        function test_all() {
          for input in ${inputs[@]}
          do
            test "$input"
          done
        }

        echo "Built-in..."
        printf "" > moeaframework.properties
        test_all

        echo ""
        echo "WFG (Variant 2)..."
        printf "org.moeaframework.core.indicator.hypervolume = ./wfg2 {2}\norg.moeaframework.core.indicator.hypervolume_inverted = true" > moeaframework.properties
        test_all

        echo ""
        echo "HOY..."
        printf "org.moeaframework.core.indicator.hypervolume = ./hoy {0} {1} {2} {3}\norg.moeaframework.core.indicator.hypervolume_inverted = false" > moeaframework.properties
        test_all
