name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile HOY
      run: |
        pushd HOY
        make
    - name: Compile WFG
      run: |
        pushd WFG
        make
    - name: Compare Timings
      run: |
        VERSION=$(curl https://api.github.com/repos/MOEAFramework/MOEAFramework/releases/latest | jq '.tag_name' | grep -oEi '[0-9]+\.[0-9]+(\.[0-9]+)?')
        wget https://github.com/MOEAFramework/MOEAFramework/releases/download/v${VERSION}/MOEAFramework-${VERSION}.tar.gz
        tar -xzf MOEAFramework-${VERSION}.tar.gz
        ls .

